apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xyne
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xyne
    app.kubernetes.io/part-of: ci10t-776-0010-app
  name: devfile-sample-xyne
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xyne
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xyne
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0010-tenant/ci10t-776-0010-app/devfile-sample-xyne@sha256:168e03c3bb68f94b6412f3519f2e134b0cc1f6d358b6e9b7b60ada178f7d428c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
